/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("java")
    id("application")
    id("org.openjfx.javafxplugin") version "0.1.0"
    id("com.github.johnrengelman.shadow") version "8.1.1"
}
java {                                      
    sourceCompatibility = JavaVersion.VERSION_21
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()  // Maven Centralから依存関係を取得
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("org.openjfx:javafx-controls:21")
    implementation("org.openjfx:javafx-graphics:21")
    implementation("org.openjfx:javafx-fxml:21")
    implementation("org.openjfx:javafx-base:21")
    implementation("org.fxyz3d:fxyz3d:0.6.0") // FXyzの依存関係

    implementation("org.matheclipse:matheclipse-core:3.0.0")//Symja

    implementation("org.apache.logging.log4j:log4j-core:2.23.1") //ロギングに関する警告の回避
    implementation("org.apache.logging.log4j:log4j-api:2.23.1") 
    implementation("org.slf4j:slf4j-reload4j:2.0.16") 
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass.set("jp.ac.uryukyu.ie.e245726.Main")
    applicationDefaultJvmArgs = listOf(
        "--add-modules=javafx.controls,javafx.graphics,javafx.fxml"
    )
}

javafx {
    version = "23.0.1"
    modules = listOf("javafx.controls", "javafx.fxml","javafx.graphics")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.named<JavaExec>("run") {
    jvmArgs(
        "--module-path", "/Users/uta/Downloads/javafx-sdk-23.0.1/lib",//パス
        "--add-modules", "javafx.controls,javafx.fxml,javafx.graphics"
    )
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "jp.ac.uryukyu.ie.e245726.Main", // Mainクラスを指定
            "Class-Path" to "/Users/uta/Downloads/javafx-sdk-23.0.1/lib/" // JavaFXライブラリのパス
        )
    }
}

tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
    archiveBaseName.set("app")
    archiveClassifier.set("") // クラス名を設定しない
    archiveVersion.set("")    // バージョンを含めない
    manifest {
        attributes(
            "Main-Class" to "jp.ac.uryukyu.ie.e245726.Main"
        )
    }
}