/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import jp.ac.uryukyu.ie.e245726.FunctionSimpler;
import jp.ac.uryukyu.ie.e245726.CreateMesh;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class Graphic3DTest {
    @Test
    void ListIndexTest(){
        ArrayList<ArrayList<ArrayList<float[]>>> outerWall = new ArrayList<>();
        ArrayList<ArrayList<float[]>> innerWall = new ArrayList<>();
        ArrayList<float[]> wall = new ArrayList<>();
        innerWall.add(wall);
        assertEquals(innerWall.size(), 1);
    }       

    @Test
    void ListIndexTest2(){
        ArrayList<ArrayList<ArrayList<float[]>>> outerWall = new ArrayList<>();
        ArrayList<float[]> wall = new ArrayList<>();
        for (int r = 0; r <= 3; r++) {
            ArrayList<ArrayList<float[]>> innerWall = new ArrayList<>();
        for (int θ = 0; θ <= 2; θ++){
            innerWall.add(wall);
            }
            assertEquals(innerWall.size(), 3);
            outerWall.add(innerWall);
        }
        assertEquals(outerWall.size(), 4);
    }

}
    

    

